spring:
  main:
    lazy-initialization: true
  data:
    mongodb:
      uri: mongodb+srv://adminuser:adminuser@cluster0.2smm7.mongodb.net/?retryWrites=true&w=majority
      database: Restaurant
      auto-index-creation: true

logging:
  file:
    name: log/myapplication.log